# Generated by Django 2.2.1 on 2019-06-02 07:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ticket cost')),
                ('travel_time', models.CharField(blank=True, max_length=40, null=True, verbose_name='Travel time')),
                ('length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Route length')),
                ('car_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car used')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Stop name')),
                ('time_table', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Route')),
            ],
        ),
    ]
